### ISSUE TITLE
可乐阅读2.14 运行报错

### ISSUE THREAD

**Issue by ThekingMX1998** [huaji8/huajiScript#12]
错误日志
` File "/ql/data/scripts/huaji8_huajiScript/可乐阅读2.14A.swap.py", line 67
    exec((lambda c: compile(c, '<string>'， 'exec'))(zlib.decompress(lzma.decompress(bz2.decompress(gzip.decompress(base64.b64decode('OMIT'))))).decode()))
                                         ^
SyntaxError: invalid character '，' (U+FF0C)`

青龙版本 `whyour/qinglong:2.17.9`

**Comment by huaji8** [comment]
属于青龙bug 无解
