### ISSUE TITLE
可乐2.14B结尾【。】号错误

### ISSUE THREAD

**Issue by AzirX1337** [huaji8/huajiScript#13]
![image](https://github.com/user-attachments/assets/5dbc2feb-a4d6-4ed0-9278-02b5db3e1a8c)
![image](https://github.com/user-attachments/assets/6d110456-efef-4391-b255-4044ae3298be)
脚本跑不起来显示符号问题，如图处，改为【.】后正常

**Comment by huaji8** [comment]
属于青龙高版本bug，只能自己改
