### ISSUE TITLE
久益阅读.py运行报错识别二维码失败

### ISSUE THREAD

**Issue by Hotwill** [huaji8/huajiScript#15]
--------开始第1个账号--------
[ERROR] ===> 识别二维码失败:[{'error': "name 'base64' is not defined", 'status_code': 500}]
[INFO] ===> 用户名:[书],余额:[0.00]

大佬看一下，这个报错是什么原因

**Comment by iainiRX** [comment]
**_我也遇到这个问题了_**

**Comment by huaji8** [comment]
台子太烂了 懒得修
